# Prevent indexing and embedding for all files
[[headers]]
  for = "/*"  # Applies to all files
  [headers.values]
    X-Robots-Tag = "noindex"  # Prevents indexing by search engines
    X-Frame-Options = "DENY"  # Prevents embedding
    Referrer-Policy = "no-referrer"  # Controls referrer information

# Allow CORS for specific JSON files
[[headers]]
  for = "/html5_questions/html5_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    X-Robots-Tag = "none"  # Override global noindex
    X-Frame-Options = "ALLOW"  # Allow embedding if necessary

[[headers]]
  for = "/css3_questions/css3_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    X-Robots-Tag = "none"  # Override global noindex
    X-Frame-Options = "ALLOW"  # Allow embedding if necessary

[[headers]]
  for = "/js_questions/js_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    X-Robots-Tag = "none"  # Override global noindex
    X-Frame-Options = "ALLOW"  # Allow embedding if necessary

[[headers]]
  for = "/react_questions/react_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    X-Robots-Tag = "none"  # Override global noindex
    X-Frame-Options = "ALLOW"  # Allow embedding if necessary

# Redirect all direct access to the JSON files to a 404 page
[[redirects]]
  from = "/html5_questions/html5_questions.json"
  to = "/404.html"
  status = 403
  force = true
  conditions = { referrer = "https://fullstack-developer-quiz.vercel.app" }

[[redirects]]
  from = "/css3_questions/css3_questions.json"
  to = "/404.html"
  status = 403
  force = true
  conditions = { referrer = "https://fullstack-developer-quiz.vercel.app" }

[[redirects]]
  from = "/js_questions/js_questions.json"
  to = "/404.html"
  status = 403
  force = true
  conditions = { referrer = "https://fullstack-developer-quiz.vercel.app" }

[[redirects]]
  from = "/react_questions/react_questions.json"
  to = "/404.html"
  status = 403
  force = true
  conditions = { referrer = "https://fullstack-developer-quiz.vercel.app" }
