[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/html5_questions/html5_questions.json"
  to = "/404.html"
  status = 403
  conditions = { referrer = "" } # Prevent direct access

[[redirects]]
  from = "/css3_questions/css3_questions.json"
  to = "/404.html"
  status = 403
  conditions = { referrer = "" } # Prevent direct access

[[redirects]]
  from = "/js_questions/js_questions.json"
  to = "/404.html"
  status = 403
  conditions = { referrer = "" } # Prevent direct access

[[redirects]]
  from = "/react_questions/react_questions.json"
  to = "/404.html"
  status = 403
  conditions = { referrer = "" } # Prevent direct access

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
