# Prevent indexing and embedding for all files
[[headers]]
  for = "/*"  # Applies to all files
  [headers.values]
    X-Robots-Tag = "noindex"  # Prevents indexing by search engines
    X-Frame-Options = "DENY"  # Prevents embedding
    Referrer-Policy = "no-referrer"  # Hides referrer

# Allow CORS for specific JSON files
[[headers]]
  for = "/html5_questions/html5_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css3_questions/css3_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/js_questions/js_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/react_questions/react_questions.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://fullstack-developer-quiz.vercel.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    Referrer-Policy = "strict-origin-when-cross-origin"

